<a href="https://colab.research.google.com/github/JayeshPatil1234/Smart-Energy-Consumption-Analysis-and-Prediction-using-Machine-Learning-with-Device-Level-Insights/blob/jayesh-patil/notebooks/feature_engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("/content/smart_home_energy_consumption_large.csv")

print(df.columns)
df.head()

Index(['Home ID', 'Appliance Type', 'Energy Consumption (kWh)', 'Time', 'Date',
       'Outdoor Temperature (°C)', 'Season', 'Household Size'],
      dtype='object')

,Home ID,Appliance Type,Energy Consumption (kWh),Time,Date,Outdoor Temperature (°C),Season,Household Size
0,94,Fridge,0.20,21:12,2023-12-02,-1.0,Fall,2
1,435,Oven,0.23,20:11,2023-08-06,31.1,Summer,5
2,466,Dishwasher,0.32,06:39,2023-11-21,21.3,Fall,3
3,496,Heater,3.92,21:56,2023-01-21,-4.2,Winter,1
4,137,Microwave,0.44,04:31,2023-08-26,34.5,Summer,5

In [ ]:
df.columns = df.columns.str.strip()

In [ ]:
df["timestamp"] = pd.to_datetime(
    df["Date"].astype(str) + " " + df["Time"].astype(str),
    errors="coerce"
)

df = df.sort_values("timestamp")
df[["Date", "Time", "timestamp"]].head()

             Date   Time           timestamp
51495  2023-01-01  00:07 2023-01-01 00:07:00
26489  2023-01-01  00:13 2023-01-01 00:13:00
8690   2023-01-01  00:24 2023-01-01 00:24:00
33315  2023-01-01  00:26 2023-01-01 00:26:00
93438  2023-01-01  00:30 2023-01-01 00:30:00

In [ ]:
df["hour"] = df["timestamp"].dt.hour
df["day"] = df["timestamp"].dt.day
df["weekday"] = df["timestamp"].dt.weekday
df["month"] = df["timestamp"].dt.month

df[["timestamp", "hour", "weekday", "month"]].head()

                timestamp  hour  weekday  month
51495 2023-01-01 00:07:00     0        6      1
26489 2023-01-01 00:13:00     0        6      1
8690  2023-01-01 00:24:00     0        6      1
33315 2023-01-01 00:26:00     0        6      1
93438 2023-01-01 00:30:00     0        6      1

In [ ]:
df["lag_1"] = df["Energy Consumption (kWh)"].shift(1)
df["lag_24"] = df["Energy Consumption (kWh)"].shift(24)

In [ ]:
df["rolling_mean_24"] = (
    df["Energy Consumption (kWh)"]
    .rolling(window=24)
    .mean()
)

In [ ]:
df = pd.get_dummies(
    df,
    columns=["Appliance Type", "Season"],
    drop_first=True
)

In [ ]:
df = df.drop(columns=["Date", "Time"])
df = df.dropna()

df.to_csv("feature_engineered_energy.csv", index=False)

df.shape

(99976, 24)